### ISSUE TITLE
Typos in installing_jupyter_notebook.md

### ISSUE THREAD

**Issue by critmcdonald** [mattwaite/JOUR307-Data-Journalism#3]
'Cause you'll chuckle that I put in an issue on this:
## installing_jupyter_notebook.md
- [ ] on Step 12, missing the closing tick on: `print("Hello World!")
- [ ] on Step 15, missing t in "shutting down he Jupyter server."
## introducing_jupyter_and_agate.md
- [ ] Missing s in "csv" in "is to put the colleges.cv file in the same directory that you're working in"

**Comment by mattwaite** [comment]
No chuckle here. Thanks for the help!

**Comment by miguelpaz** [comment]
I did not see license details. 
Can I fork to use for my class and if I add or adapt pull request?

**Comment by mattwaite** [comment]
It's a creative commons non-commercial share alike license: https://creativecommons.org/licenses/by-nc-sa/4.0/

Short answer: Go right ahead. I put it out there for people to use. Fork for yourself, release your own version, kick a pull request back, all is good with me.

**Comment by miguelpaz** [comment]
👍🏼👏🏼👊🏼🤘🏻🚀
